version: "3.10"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery
    command: celery -A task_manager worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
